name: frontend_karyawan_flutter
description: Frontend mobile karyawan untuk sistem absensi, lembur, activity, dan payslip.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  flutter_map: 7.0.2
  latlong2: ^0.9.1
  printing: ^5.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
