import http from "node:http";
import { randomUUID } from "node:crypto";

const PORT = Number(process.env.PORT || 3000);
const ROLE = { EMPLOYEE: "employee", ADMIN: "admin" };
const PAYROLL = { DRAFT: "draft", PUBLISHED: "published", PAID: "paid" };
const jakartaDateFormatter = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Jakarta", year: "numeric", month: "2-digit", day: "2-digit" });
const now = () => new Date().toISOString();
const today = () => jakartaDateFormatter.format(new Date());
const minutesBetween = (a, b) => Math.max(0, Math.round((new Date(b) - new Date(a)) / 60000));
const money = (value) => Math.round(Number(value || 0));

const db = {
  users: [],
  sessions: new Map(),
  employees: [],
  salaryRates: [],
  attendance: [],
  overtime: [],
  cashbon: [],
  cashbonDeductions: [],
  payrolls: [],
  payslips: [],
  auditLogs: []
};

function send(res, status, body = {}) {
  res.writeHead(status, { "Content-Type": "application/json; charset=utf-8", "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "Content-Type, Authorization", "Access-Control-Allow-Methods": "GET,POST,PUT,PATCH,DELETE,OPTIONS" });
  res.end(JSON.stringify(body));
}

function fail(res, status, message) { send(res, status, { error: { message } }); }
async function body(req) { const chunks = []; for await (const c of req) chunks.push(c); const text = Buffer.concat(chunks).toString("utf8"); return text.trim() ? JSON.parse(text) : {}; }
function publicUser(user) { return { id: user.id, name: user.name, username: user.username, role: user.role, employee_id: user.employee_id }; }
function userFromReq(req) { const token = (req.headers.authorization || "").replace(/^Bearer /, ""); const id = db.sessions.get(token); return db.users.find((u) => u.id === id) || null; }
function auth(req, res) { const user = userFromReq(req); if (!user) fail(res, 401, "Login diperlukan."); return user; }
function admin(req, res) { const user = auth(req, res); if (!user) return null; if (user.role !== ROLE.ADMIN) { fail(res, 403, "Akses hanya untuk Admin/Owner."); return null; } return user; }
function can(user, employeeId) { return user.role === ROLE.ADMIN || user.employee_id === employeeId; }
function audit(user, module, recordId, action, oldValue = null, newValue = null) { db.auditLogs.push({ id: randomUUID(), user_id: user?.id || null, module, record_id: recordId, action, old_value: oldValue, new_value: newValue, timestamp: now() }); }
function rate(employeeId) { return db.salaryRates.find((item) => item.employee_id === employeeId); }
function balance(employeeId) { return db.cashbon.filter((c) => c.employee_id === employeeId && c.status === "approved").reduce((s, c) => s + c.amount, 0) - db.cashbonDeductions.filter((d) => d.employee_id === employeeId).reduce((s, d) => s + d.amount, 0); }
function attendanceDto(item, priv) { const result = { ...item, employee_name: db.employees.find((e) => e.id === item.employee_id)?.name || null, duration_minutes: item.check_out_time ? minutesBetween(item.check_in_time, item.check_out_time) : 0 }; if (!priv) { delete result.check_in_photo; delete result.check_in_latitude; delete result.check_in_longitude; } return result; }
function payrollDto(p, user) { const result = { ...p }; if (user.role !== ROLE.ADMIN) { delete result.daily_rate_snapshot; delete result.overtime_rate_snapshot; } return result; }
function calcPayroll(employee, start, end, deduction = 0) { const r = rate(employee.id); const att = db.attendance.filter((a) => a.employee_id === employee.id && a.date >= start && a.date <= end && ["completed", "corrected"].includes(a.status)); const ot = db.overtime.filter((o) => o.employee_id === employee.id && o.date >= start && o.date <= end && o.status === "approved"); const normal = att.length * r.daily_rate; const overtime = ot.reduce((s, o) => s + o.amount, 0); return { employee_id: employee.id, employee_name: employee.name, period_start: start, period_end: end, working_days: att.length, daily_rate_snapshot: r.daily_rate, overtime_rate_snapshot: r.overtime_rate, overtime_minutes: ot.reduce((s, o) => s + o.duration_minutes, 0), normal_salary: normal, overtime_amount: overtime, cashbon_balance: balance(employee.id), cashbon_deduction: deduction, net_salary: normal + overtime - deduction }; }

const routes = [];
function route(method, pattern, handler) { const keys = []; const rx = new RegExp("^" + pattern.replace(/:([A-Za-z0-9_]+)/g, (_, k) => { keys.push(k); return "([^/]+)"; }) + "$", "i"); routes.push({ method, rx, keys, handler }); }
function match(method, path) { for (const r of routes) { if (r.method !== method) continue; const m = path.match(r.rx); if (m) return { handler: r.handler, params: Object.fromEntries(r.keys.map((k, i) => [k, decodeURIComponent(m[i + 1])])) }; } return null; }

route("GET", "/api/health", async (_req, res) => send(res, 200, { status: "ok", database: "local-memory", time: now() }));
route("POST", "/api/auth/login", async (req, res) => { const b = await body(req); const user = db.users.find((u) => u.username === b.username && u.password === b.password && u.status === "active"); if (!user) return fail(res, 401, "Username atau password salah."); const token = randomUUID(); db.sessions.set(token, user.id); send(res, 200, { token, user: publicUser(user) }); });
route("POST", "/api/auth/register", async (req, res) => { const b = await body(req); const name = String(b.name || "").trim(); const username = String(b.username || "").trim().toLowerCase(); const password = String(b.password || ""); if (name.length < 3 || username.length < 3 || password.length < 6) return fail(res, 422, "Nama, username, dan password wajib valid."); if (db.users.some((u) => u.username.toLowerCase() === username)) return fail(res, 409, "Username sudah digunakan."); const userId = randomUUID(); const employeeId = randomUUID(); const user = { id: userId, name, username, password, role: ROLE.EMPLOYEE, employee_id: employeeId, status: "active" }; const employee = { id: employeeId, user_id: userId, employee_code: `EMP-${String(db.employees.length + 1).padStart(3, "0")}`, name, status: "active", created_at: now() }; db.users.push(user); db.employees.push(employee); db.salaryRates.push({ id: randomUUID(), employee_id: employeeId, daily_rate: 150000, overtime_rate: 30000, effective_date: today(), updated_by: null, updated_at: now() }); audit(user, "auth", userId, "register", null, publicUser(user)); const token = randomUUID(); db.sessions.set(token, user.id); send(res, 201, { token, user: publicUser(user) }); });
route("POST", "/api/auth/register-admin", async (req, res) => { if (db.users.some((u) => u.role === ROLE.ADMIN && u.status === "active")) return fail(res, 409, "Admin pertama sudah dibuat."); const b = await body(req); const name = String(b.name || "").trim(); const username = String(b.username || "").trim().toLowerCase(); const password = String(b.password || ""); if (name.length < 3 || username.length < 3 || password.length < 6) return fail(res, 422, "Nama, username, dan password wajib valid."); if (db.users.some((u) => u.username.toLowerCase() === username)) return fail(res, 409, "Username sudah digunakan."); const user = { id: randomUUID(), name, username, password, role: ROLE.ADMIN, employee_id: null, status: "active" }; db.users.push(user); audit(user, "auth", user.id, "register_admin", null, publicUser(user)); const token = randomUUID(); db.sessions.set(token, user.id); send(res, 201, { token, user: publicUser(user) }); });
route("GET", "/api/auth/me", async (req, res) => { const user = auth(req, res); if (user) send(res, 200, { user: publicUser(user) }); });
route("GET", "/api/employees", async (req, res) => { if (admin(req, res)) send(res, 200, { employees: db.employees }); });
route("GET", "/api/employees/:id", async (req, res, p) => { const user = auth(req, res); if (!user) return; if (!can(user, p.id)) return fail(res, 403, "Tidak boleh melihat data karyawan ini."); send(res, 200, { employee: db.employees.find((e) => e.id === p.id) || null }); });
route("GET", "/api/employees/:id/salary-rate", async (req, res, p) => { if (admin(req, res)) send(res, 200, { salary_rate: rate(p.id) }); });
route("PUT", "/api/employees/:id/salary-rate", async (req, res, p) => { const user = admin(req, res); if (!user) return; const b = await body(req); if (!b.daily_rate || !b.overtime_rate) return fail(res, 422, "Daily rate dan overtime rate wajib diisi."); const next = { id: randomUUID(), employee_id: p.id, daily_rate: money(b.daily_rate), overtime_rate: money(b.overtime_rate), effective_date: b.effective_date || today(), updated_by: user.id, updated_at: now() }; db.salaryRates.push(next); audit(user, "salary_rate", next.id, "update", null, next); send(res, 200, { salary_rate: next }); });

route("GET", "/api/attendance/today", async (req, res) => { const user = auth(req, res); if (!user) return; const url = new URL(req.url, `http://${req.headers.host}`); const employeeId = user.role === ROLE.ADMIN ? url.searchParams.get("employee_id") : user.employee_id; const item = db.attendance.find((a) => a.employee_id === employeeId && a.date === today()); send(res, 200, { attendance: item ? attendanceDto(item, user.role === ROLE.ADMIN || user.employee_id === employeeId) : null }); });
route("POST", "/api/attendance/check-in", async (req, res) => { const user = auth(req, res); if (!user) return; if (user.role !== ROLE.EMPLOYEE) return fail(res, 403, "Check-in hanya untuk karyawan."); const b = await body(req); if (!b.project_name) return fail(res, 422, "Proyek/lokasi kerja wajib diisi."); if (!b.photo) return fail(res, 422, "Foto bukti wajib tersedia sebelum Check-in."); if (!Number.isFinite(Number(b.latitude)) || !Number.isFinite(Number(b.longitude))) return fail(res, 422, "Latitude dan longitude wajib valid."); if (db.attendance.some((a) => a.employee_id === user.employee_id && a.date === today())) return fail(res, 409, "Karyawan sudah memiliki attendance hari ini."); const item = { id: randomUUID(), employee_id: user.employee_id, date: today(), project_name: b.project_name, check_in_time: now(), check_in_latitude: Number(b.latitude), check_in_longitude: Number(b.longitude), check_in_photo: b.photo, check_out_time: null, notes: b.notes || "", status: "running", created_at: now(), updated_at: now() }; db.attendance.push(item); audit(user, "attendance", item.id, "check_in", null, item); send(res, 201, { attendance: item }); });
route("POST", "/api/attendance/check-out", async (req, res) => { const user = auth(req, res); if (!user) return; const item = db.attendance.find((a) => a.employee_id === user.employee_id && a.status === "running"); if (!item) return fail(res, 409, "Tidak ada attendance aktif untuk Check-out."); const before = { ...item }; item.check_out_time = now(); item.status = "completed"; item.updated_at = now(); audit(user, "attendance", item.id, "check_out", before, item); send(res, 200, { attendance: item, duration_minutes: minutesBetween(item.check_in_time, item.check_out_time) }); });
route("GET", "/api/attendance/history", async (req, res) => { const user = auth(req, res); if (!user) return; const url = new URL(req.url, `http://${req.headers.host}`); const employeeId = user.role === ROLE.ADMIN ? url.searchParams.get("employee_id") : user.employee_id; send(res, 200, { attendance: db.attendance.filter((a) => !employeeId || a.employee_id === employeeId).map((a) => attendanceDto(a, user.role === ROLE.ADMIN || user.employee_id === a.employee_id)) }); });
route("GET", "/api/attendance", async (req, res) => { const user = admin(req, res); if (user) send(res, 200, { attendance: db.attendance.map((a) => attendanceDto(a, true)) }); });
route("GET", "/api/attendance/:id", async (req, res, p) => { const user = auth(req, res); if (!user) return; const item = db.attendance.find((a) => a.id === p.id); if (!item) return fail(res, 404, "Attendance tidak ditemukan."); if (!can(user, item.employee_id)) return fail(res, 403, "Tidak boleh melihat attendance ini."); send(res, 200, { attendance: attendanceDto(item, user.role === ROLE.ADMIN || user.employee_id === item.employee_id) }); });
route("PATCH", "/api/attendance/:id/adjust", async (req, res, p) => { const user = admin(req, res); if (!user) return; const b = await body(req); const item = db.attendance.find((a) => a.id === p.id); if (!item) return fail(res, 404, "Attendance tidak ditemukan."); const before = { ...item }; Object.assign(item, { project_name: b.project_name ?? item.project_name, check_in_time: b.check_in_time ?? item.check_in_time, check_out_time: b.check_out_time ?? item.check_out_time, notes: b.notes ?? item.notes, status: b.status ?? "corrected", updated_at: now() }); audit(user, "attendance", item.id, "adjust", before, { ...item, reason: b.reason }); send(res, 200, { attendance: item }); });

route("GET", "/api/activity", async (req, res) => { const user = auth(req, res); if (!user) return; const date = new URL(req.url, `http://${req.headers.host}`).searchParams.get("date") || today(); const activity = db.employees.map((e) => { const a = db.attendance.find((x) => x.employee_id === e.id && x.date === date); const ot = db.overtime.find((x) => x.employee_id === e.id && x.date === date && x.status === "running"); return { employee_id: e.id, employee_name: e.name, status: ot ? "lembur_berjalan" : a?.status === "running" ? "masuk" : a?.check_out_time ? "pulang" : "belum_masuk", time: ot?.start_time || a?.check_out_time || a?.check_in_time || null, project_name: ot?.project_name || a?.project_name || null, date }; }); send(res, 200, { activity }); });
route("GET", "/api/admin/dashboard", async (req, res) => { if (!admin(req, res)) return; const date = new URL(req.url, `http://${req.headers.host}`).searchParams.get("date") || today(); const masuk = db.attendance.filter((a) => a.date === date && a.status === "running").length; const belumMasuk = db.employees.length - db.attendance.filter((a) => a.date === date).length; const lembur = db.overtime.filter((o) => o.date === date && o.status === "running").length; const pendingOvertime = db.overtime.filter((o) => o.status === "completed").length; send(res, 200, { date, summary: { masuk, belum_masuk: belumMasuk, lembur, pending_overtime: pendingOvertime } }); });

route("POST", "/api/overtime/start", async (req, res) => { const user = auth(req, res); if (!user) return; const b = await body(req); const a = db.attendance.find((x) => x.employee_id === user.employee_id && x.date === today() && x.status === "completed"); if (!a) return fail(res, 409, "Lembur baru bisa dimulai setelah Check-out kerja normal."); if (!b.project_name || !b.description || !b.photo) return fail(res, 422, "Proyek, keterangan, dan foto lembur wajib diisi."); const r = rate(user.employee_id); const item = { id: randomUUID(), employee_id: user.employee_id, attendance_id: a.id, date: today(), project_name: b.project_name, description: b.description, photo: b.photo, latitude: Number(b.latitude), longitude: Number(b.longitude), start_time: now(), end_time: null, duration_minutes: 0, rate: r.overtime_rate, amount: 0, status: "running" }; db.overtime.push(item); audit(user, "overtime", item.id, "start", null, item); send(res, 201, { overtime: item }); });
route("POST", "/api/overtime/:id/finish", async (req, res, p) => { const user = auth(req, res); if (!user) return; const item = db.overtime.find((o) => o.id === p.id && o.employee_id === user.employee_id); if (!item || item.status !== "running") return fail(res, 409, "Lembur tidak sedang berjalan."); const before = { ...item }; item.end_time = now(); item.duration_minutes = minutesBetween(item.start_time, item.end_time); item.amount = money((item.duration_minutes / 60) * item.rate); item.status = "completed"; audit(user, "overtime", item.id, "finish", before, item); send(res, 200, { overtime: item }); });
route("GET", "/api/overtime/history", async (req, res) => { const user = auth(req, res); if (!user) return; const employeeId = user.role === ROLE.ADMIN ? new URL(req.url, `http://${req.headers.host}`).searchParams.get("employee_id") : user.employee_id; send(res, 200, { overtime: db.overtime.filter((o) => !employeeId || o.employee_id === employeeId) }); });
route("GET", "/api/overtime/pending", async (req, res) => { if (admin(req, res)) send(res, 200, { overtime: db.overtime.filter((o) => o.status === "completed") }); });
route("POST", "/api/overtime/:id/review", async (req, res, p) => { const user = admin(req, res); if (!user) return; const b = await body(req); const item = db.overtime.find((o) => o.id === p.id); if (!item) return fail(res, 404, "Lembur tidak ditemukan."); const before = { ...item }; if (b.action === "approve") item.status = "approved"; else if (b.action === "reject") item.status = "rejected"; else if (b.action === "correct") { item.duration_minutes = Number(b.duration_minutes); item.amount = money((item.duration_minutes / 60) * item.rate); item.status = "corrected"; } else return fail(res, 422, "action harus approve, reject, atau correct."); item.reviewed_by = user.id; item.reviewed_at = now(); audit(user, "overtime", item.id, `review_${b.action}`, before, item); send(res, 200, { overtime: item }); });

route("GET", "/api/cashbon", async (req, res) => { const user = auth(req, res); if (!user) return; const employeeId = user.role === ROLE.ADMIN ? new URL(req.url, `http://${req.headers.host}`).searchParams.get("employee_id") : user.employee_id; const ledger = [...db.cashbon.filter((c) => c.employee_id === employeeId).map((c) => ({ type: "cashbon", id: c.id, date: c.transaction_date, amount: c.amount, description: c.description, status: c.status })), ...db.cashbonDeductions.filter((d) => d.employee_id === employeeId).map((d) => ({ type: "deduction", id: d.id, date: d.created_at.slice(0, 10), amount: -d.amount, description: "Potongan Payroll", payroll_id: d.payroll_id }))]; send(res, 200, { balance: balance(employeeId), ledger }); });
route("POST", "/api/cashbon", async (req, res) => { const user = admin(req, res); if (!user) return; const b = await body(req); const item = { id: randomUUID(), employee_id: b.employee_id, transaction_date: b.transaction_date || today(), amount: money(b.amount), description: b.description || "Cashbon", status: b.status || "approved", created_by: user.id, created_at: now() }; db.cashbon.push(item); audit(user, "cashbon", item.id, "create", null, item); send(res, 201, { cashbon: item, balance: balance(item.employee_id) }); });
route("GET", "/api/cashbon/:employeeId/balance", async (req, res, p) => { const user = auth(req, res); if (user && can(user, p.employeeId)) send(res, 200, { employee_id: p.employeeId, balance: balance(p.employeeId) }); else if (user) fail(res, 403, "Tidak boleh melihat saldo cashbon ini."); });

route("POST", "/api/payroll/generate", async (req, res) => { const user = admin(req, res); if (!user) return; const b = await body(req); db.payrolls = db.payrolls.filter((p) => !(p.period_start === b.period_start && p.period_end === b.period_end && p.status === PAYROLL.DRAFT)); const rows = db.employees.map((e) => ({ id: randomUUID(), ...calcPayroll(e, b.period_start, b.period_end, 0), status: PAYROLL.DRAFT, published_at: null, published_by: null, paid_at: null, paid_by: null, created_by: user.id, created_at: now(), updated_at: now() })); db.payrolls.push(...rows); audit(user, "payroll", `${b.period_start}_${b.period_end}`, "generate", null, rows.map((p) => p.id)); send(res, 201, { payrolls: rows }); });
route("GET", "/api/payroll", async (req, res) => { const user = admin(req, res); if (user) send(res, 200, { payrolls: db.payrolls }); });
route("GET", "/api/payroll/:id", async (req, res, p) => { const user = auth(req, res); if (!user) return; const item = db.payrolls.find((x) => x.id === p.id); if (!item) return fail(res, 404, "Payroll tidak ditemukan."); if (!can(user, item.employee_id)) return fail(res, 403, "Tidak boleh melihat payroll ini."); if (user.role === ROLE.EMPLOYEE && ![PAYROLL.PUBLISHED, PAYROLL.PAID].includes(item.status)) return fail(res, 403, "Payslip belum diterbitkan."); send(res, 200, { payroll: payrollDto(item, user) }); });
route("PATCH", "/api/payroll/:id/cashbon-deduction", async (req, res, p) => { const user = admin(req, res); if (!user) return; const b = await body(req); const item = db.payrolls.find((x) => x.id === p.id); if (!item) return fail(res, 404, "Payroll tidak ditemukan."); const amount = money(b.amount); if (amount > balance(item.employee_id)) return fail(res, 422, "Potongan cashbon tidak boleh lebih besar dari saldo aktif."); item.cashbon_deduction = amount; item.cashbon_balance = balance(item.employee_id); item.net_salary = item.normal_salary + item.overtime_amount - amount; item.status = "reviewed"; send(res, 200, { payroll: item, remaining_cashbon_after_payroll: item.cashbon_balance - amount }); });
route("POST", "/api/payroll/:id/publish", async (req, res, p) => { const user = admin(req, res); if (!user) return; const item = db.payrolls.find((x) => x.id === p.id); if (!item) return fail(res, 404, "Payroll tidak ditemukan."); if (db.overtime.some((o) => o.employee_id === item.employee_id && o.date >= item.period_start && o.date <= item.period_end && o.status === "completed")) return fail(res, 409, "Masih ada lembur yang perlu review sebelum publish."); item.status = PAYROLL.PUBLISHED; item.published_at = now(); item.published_by = user.id; if (item.cashbon_deduction > 0) db.cashbonDeductions.push({ id: randomUUID(), cashbon_id: db.cashbon.find((c) => c.employee_id === item.employee_id)?.id, employee_id: item.employee_id, payroll_id: item.id, amount: item.cashbon_deduction, created_by: user.id, created_at: now() }); const payslip = { id: randomUUID(), payroll_id: item.id, employee_id: item.employee_id, issued_at: now(), issued_by: user.id }; db.payslips.push(payslip); send(res, 200, { payroll: item, payslip }); });
route("POST", "/api/payroll/publish-period", async (req, res) => { const user = admin(req, res); if (!user) return; const b = await body(req); const rows = db.payrolls.filter((p) => p.period_start === b.period_start && p.period_end === b.period_end && [PAYROLL.DRAFT, "reviewed"].includes(p.status)); for (const item of rows) { item.status = PAYROLL.PUBLISHED; item.published_at = now(); item.published_by = user.id; db.payslips.push({ id: randomUUID(), payroll_id: item.id, employee_id: item.employee_id, issued_at: now(), issued_by: user.id }); } send(res, 200, { published_count: rows.length, payrolls: rows }); });
route("POST", "/api/payroll/:id/mark-paid", async (req, res, p) => { const user = admin(req, res); if (!user) return; const item = db.payrolls.find((x) => x.id === p.id); if (!item) return fail(res, 404, "Payroll tidak ditemukan."); item.status = PAYROLL.PAID; item.paid_at = now(); item.paid_by = user.id; send(res, 200, { payroll: item }); });
route("GET", "/api/payslips", async (req, res) => { const user = auth(req, res); if (!user) return; const employeeId = user.role === ROLE.ADMIN ? new URL(req.url, `http://${req.headers.host}`).searchParams.get("employee_id") : user.employee_id; const payslips = db.payslips.filter((ps) => ps.employee_id === employeeId).map((ps) => ({ ...ps, payroll: payrollDto(db.payrolls.find((p) => p.id === ps.payroll_id), user) })); send(res, 200, { payslips }); });
route("GET", "/api/payslips/:id", async (req, res, p) => { const user = auth(req, res); if (!user) return; const ps = db.payslips.find((x) => x.id === p.id); if (!ps) return fail(res, 404, "Payslip tidak ditemukan."); send(res, 200, { payslip: ps, payroll: payrollDto(db.payrolls.find((x) => x.id === ps.payroll_id), user) }); });
route("GET", "/api/audit-logs", async (req, res) => { if (admin(req, res)) send(res, 200, { audit_logs: db.auditLogs }); });

const server = http.createServer(async (req, res) => {
  if (req.method === "OPTIONS") return send(res, 204);
  const url = new URL(req.url, `http://${req.headers.host}`);
  const found = match(req.method, url.pathname);
  if (!found) return fail(res, 404, "Endpoint tidak ditemukan.");
  try { await found.handler(req, res, found.params); } catch (err) { fail(res, err.status || 500, err.status ? err.message : "Terjadi kesalahan server."); }
});

server.listen(PORT, () => console.log(`Local memory backend listening on http://localhost:${PORT}`));
